[package]
name = "yt-pu"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.27"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde_json = "1.0.138"
strsim = "0.11.1"
trash = "5.2.1"
